### ISSUE TITLE
Librerías de GLMM

### ISSUE THREAD

**Issue by nepito** [IslasGECI/glmm#1]
Necesitamos estas librerías de :r: para hacer el análisis necesarios de éxito de volantón:
`car`, `emmeans`, `ggpubr`, `lme4` y `MuMIn`.

**Comment by devarops** [comment]
Parece que ya quedó resuelto [aquí](https://github.com/IslasGECI/servidor/commit/f7af4617b2949c6bb6cdb0f3fff80d95d2d769f0)
